# - Config file for DoorCloser
# - If you make any changes to this file, you must 
# - reload the config using the "/doorcloser reload" command.

# - This plugin is written by Kirastur
# - Please visit our homepage at
# -   https://www.spigotmc.org/resources/doorcloser-butler.90762
# - 
# - There you can find a link to our support page   

# - This work contains code from the original DoorCloser-Plugin written by Psychlist1972
# - He has released his work using the Apache 2.0 license
# - Please see https://github.com/Psychlist1972/Minecraft-DoorCloser for reference

# If any of the values is not parseable, a default value is used
# If a material is not known or not an openable, the configuration is rejected

# Time: Time (in seconds as integer) to allow the door to remain open
# This is an estimate. How long it really stays open depends
# on how quickly Spigot can get to the event handler. It won't
# be faster than this, but will typically be slower, again, 
# depending upon server load, number of plugins running, etc.
Time: 5

# IgnoreIfInCreative: true if you want to ignore the door when the player 
# is in creative mode. If this is not set to true, you'll never be able to 
# create an open door unless you turn on sneaking.
IgnoreIfInCreative: true

# IgnoreIfSneaking: true if you want to ignore the door when the player is 
# sneaking. This will work for all players, not just someone in creative
IgnoreIfSneaking: false

# PlaySound: True if the door/gate/trapdoor closing sound should be played
PlaySound: true

# SynchronizeDoubleDoor: automatically open and close the second door
# when you click on one of the doors in a pair. Detection algorithm
# checks for where the hinges are located.
SynchronizeDoubleDoor: true

# OptimisticDoubleDoorSync: the synchonization of the double door is
# normally done one tick later than the player interact event
# to be sure that the open was not cancelled e.g. by permission or region.
# But this leads to the effect that in a paired door the second door
# opens one tick later. To get a better optical effect you can
# be optimistic and open the paired door at the same time as the original
# door (and close it just one tick later if the open was cancelled).
OptimisticDoubleDoorSync: false

# Next you have to define the blocks (doors, gates, and trapdoors)
# that you want to auto-close.
# You have an include-list and an exclude-list.

# IncludeAllDoors, IncludeAllGates, IncludeAllTrapDoors:
# To be minecraft version independend, you have the option to add
# all materials known by this minecraft version to the include list
IncludeAllDoors: true
IncludeAllGates: true
IncludeAllTrapDoors: true

# If you decide to add door/gates/trapdoors of a specific type,
# you can use an additional include list.
# Enter the material as defined in the Spigot API
# See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#
# You can only add openable blocks here

# Please uncomment the following lines if you want to use this feature 
#Include:
#- ACACIA_DOOR
#- BIRCH_FENCE_GATE
  
# If you have added all materials, and you only want to
# remove a dedicated material, you can use the exclude list
# Exclude takes precedence over include

# Please uncomment the following lines if you want to use this feature 
#Exclude:
#- CRIMSON_DOOR
#- CRIMSON_FENCE_GATE 
#- CRIMSON_TRAPDOOR

# Materials are ignored by the SynchronizeDoubleDoor-Feature
#
# Warning: Do not delete or comment-out all blocks from a list
# Instead comment-out the list itself.
